#!/usr/bin/env python3
"""Full-history saved-state guarded residual MAPPO for LuST/SUMO 0.27.

Unlike direct --begin experiments, every branch loads a state generated by a
native full-day trajectory 300 s before the operating window. Actuated and
MAPPO evaluation branches therefore start from the exact same network state.
"""
import argparse,csv,json,os,random,sys,time
import numpy as np
import torch

sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from train_mappo_legacy_residual import Env,MAPPO,rollout,read_csv,write_csv

class SavedEnv(Env):
    def __init__(self,traci,scenario,selection,control_start_s,control_s,seed,state_path,
                 prehistory_s=300,**kwargs):
        super().__init__(traci,scenario,selection,control_start_s,control_s,seed,
                         warmup_s=prehistory_s,**kwargs)
        self.state_path=os.path.abspath(state_path)
        self.state_time=int(control_start_s-prehistory_s)
        self.prehistory_s=int(prehistory_s)

    def cmd(self):
        return [self.sumo,"-c",os.path.join(self.scenario,"due.actuated.sumocfg"),
                "--load-state",self.state_path,
                "--begin",str(self.state_time),
                "--end",str(self.end),
                "--seed",str(self.seed),
                "--summary-output","/dev/null","--tripinfo-output","/dev/null","--log","/dev/null"]

def native_saved_eval(traci,sumo,scenario,selection,control_start_s,control_s,seed,state_path,prehistory_s=300):
    env=SavedEnv(traci,scenario,selection,control_start_s,control_s,seed,state_path,prehistory_s)
    env.start(sumo)
    try:
        while env.tc.time_s()<env.end and env.tc.min_expected()>0:
            arrived=0;co2=0.
            for _ in range(env.decision_dt):
                if env.tc.min_expected()<=0:break
                env.tc.step();arrived+=env.tc.arrived_number()
                for tl in env.tls:co2+=env.lane_stats(tl)["co2"]
            stats=[env.lane_stats(t) for t in env.tls]
            env.metrics["halt"]+=sum(s["halt"] for s in stats)
            env.metrics["waiting"]+=sum(s["waiting"] for s in stats)
            env.metrics["arrived"]+=arrived
            env.metrics["co2_mg"]+=co2
            env.steps+=1
        return env.summary()
    finally:
        env.close()

def load_manifest(path):
    d=json.load(open(path))
    by={(int(r["seed"]),r["condition"]):r for r in d["records"]}
    return d,by

def aggregate(rows):
    out=[]
    metrics=["mean_halting_vehicles","mean_waiting_time_lane_sum_s",
             "arrived_vehicles_global","CO2_kg_selected_approaches",
             "intervention_rate","mask_eligible_rate"]
    for ctrl in sorted(set(r["controller"] for r in rows)):
        for cond in sorted(set(r["condition"] for r in rows)):
            rr=[r for r in rows if r["controller"]==ctrl and r["condition"]==cond]
            if not rr:continue
            o={"controller":ctrl,"condition":cond,"n_seeds":len(rr)}
            for k in metrics:
                vals=np.asarray([float(r.get(k,0.0)) for r in rr])
                o[k+"_mean"]=float(vals.mean())
                o[k+"_sd"]=float(vals.std(ddof=1)) if len(vals)>1 else 0.0
            out.append(o)
    return out

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--sumo",required=True);ap.add_argument("--sumo-tools",required=True)
    ap.add_argument("--scenario",required=True);ap.add_argument("--selection",required=True)
    ap.add_argument("--windows",required=True);ap.add_argument("--states",required=True)
    ap.add_argument("--state-manifest",required=True);ap.add_argument("--outdir",required=True)
    ap.add_argument("--episodes",type=int,default=32);ap.add_argument("--train-s",type=int,default=900)
    ap.add_argument("--eval-s",type=int,default=1800);ap.add_argument("--train-seeds",default="4101,4102")
    ap.add_argument("--eval-seeds",default="9001,9002,9003");ap.add_argument("--seed",type=int,default=42)
    args=ap.parse_args();os.makedirs(args.outdir,exist_ok=True)

    sys.path.insert(0,os.path.abspath(args.sumo_tools));import traci
    random.seed(args.seed);np.random.seed(args.seed);torch.manual_seed(args.seed)

    selection=read_csv(args.selection)
    windows={r["condition"]:int(float(r["selected_hour"])) for r in read_csv(args.windows)}
    conds=[c for c in ("Off-peak","AM","Lunch","PM") if c in windows]
    manifest,state_map=load_manifest(args.state_manifest)
    train_seeds=[int(x) for x in args.train_seeds.split(",") if x.strip()]
    eval_seeds=[int(x) for x in args.eval_seeds.split(",") if x.strip()]
    for s in train_seeds+eval_seeds:
        for c in conds:
            assert (s,c) in state_map,(s,c)

    agent=MAPPO(9,13,3,args.seed)
    hist=[];t0=time.time()
    for ep in range(args.episodes):
        cond=conds[ep%len(conds)]
        seed=train_seeds[(ep//len(conds))%len(train_seeds)]
        rec=state_map[(seed,cond)]
        state_path=os.path.join(args.states,rec["state_file"])
        env=SavedEnv(traci,args.scenario,selection,windows[cond]*3600,args.train_s,seed,state_path)
        traj,s=rollout(env,args.sumo,agent,True);up=agent.update(traj)
        row={"episode":ep+1,"condition":cond,"seed":seed,
             "state_sha256":rec["sha256"],"state_time_s":rec["state_time_s"],**s,**up}
        hist.append(row);print(row,flush=True)
    write_csv(os.path.join(args.outdir,"training_history.csv"),hist)

    policy_meta={
        "algorithm":"full-history saved-state guarded residual MAPPO",
        "simulator":"SUMO 0.27.0","episodes":args.episodes,
        "train_seeds":train_seeds,"eval_seeds":eval_seeds,
        "decision_interval_s":10,"state_prehistory_s":300,
        "actions":{"0":"native","1":"+3s remaining-green extension","2":"+6s remaining-green extension"},
        "same_state_pairing":True,
        "note":"Each controller pair loads the same state file and SHA-256 fingerprint."
    }
    torch.save({"actor":agent.actor.state_dict(),"critic":agent.critic.state_dict(),"meta":policy_meta},
               os.path.join(args.outdir,"legacy_savedstate_mappo.pt"))

    rows=[]
    for seed in eval_seeds:
        for cond in conds:
            rec=state_map[(seed,cond)];state_path=os.path.join(args.states,rec["state_file"])
            base=native_saved_eval(traci,args.sumo,args.scenario,selection,windows[cond]*3600,args.eval_s,
                                   seed,state_path)
            rows.append({"controller":"Actuated","seed":seed,"condition":cond,
                         "state_sha256":rec["sha256"],**base})
            env=SavedEnv(traci,args.scenario,selection,windows[cond]*3600,args.eval_s,seed,state_path)
            _,m=rollout(env,args.sumo,agent,False)
            rows.append({"controller":"MAPPO-residual","seed":seed,"condition":cond,
                         "state_sha256":rec["sha256"],**m})
            print(rows[-2:],flush=True)

    # Hard audit: paired branches for every seed/condition must reference identical state hashes.
    for seed in eval_seeds:
        for cond in conds:
            pair=[r for r in rows if r["seed"]==seed and r["condition"]==cond]
            assert len(pair)==2 and len({r["state_sha256"] for r in pair})==1,(seed,cond,pair)

    write_csv(os.path.join(args.outdir,"evaluation_raw.csv"),rows)
    summary=aggregate(rows);write_csv(os.path.join(args.outdir,"evaluation_summary.csv"),summary)

    paired=[]
    for seed in eval_seeds:
        for cond in conds:
            a=next(r for r in rows if r["controller"]=="Actuated" and r["seed"]==seed and r["condition"]==cond)
            m=next(r for r in rows if r["controller"]=="MAPPO-residual" and r["seed"]==seed and r["condition"]==cond)
            o={"seed":seed,"condition":cond,"state_sha256":a["state_sha256"]}
            for k,higher in [("mean_halting_vehicles",False),("mean_waiting_time_lane_sum_s",False),
                             ("arrived_vehicles_global",True),("CO2_kg_selected_approaches",False)]:
                av=float(a[k]);mv=float(m[k])
                o[k+"_rel_improvement"]=((mv-av) if higher else (av-mv))/max(abs(av),1e-12)
            paired.append(o)
    write_csv(os.path.join(args.outdir,"paired_improvements.csv"),paired)
    with open(os.path.join(args.outdir,"run_metadata.json"),"w") as f:
        json.dump({**policy_meta,"wall_time_s":time.time()-t0,
                   "state_manifest":manifest},f,indent=2)

if __name__=="__main__":
    main()
